meta_product_name: "GetAdvice"
meta_title: "GetAdvice - Apportez à vos clients le conseil dont ils ont besoin !"
meta_description: "GetAdvice permets à vos clients de faire appel à un vendeur directement depuis les rayons. "
meta_image: "pic-yaml3.jpg" # should exist in `app/assets/images/`
